# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  
  lane :custom_lane do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )

    firebase_app_distribution(
      
      app: "1:1029177077570:android:45412d04da3eab14c1a2db",
      groups: "testygroup"
    )
  end
end
