default_platform(:android)

platform :android do
  # lane :build_flutter_app do
  #   # Étape de construction de l'application Flutter
  #   sh "flutter clean"
  #   sh "flutter pub get"
  #   sh "flutter build apk --release" # Remplacez par "flutter build appbundle --release" pour générer un bundle d'application (.aab)
  # end

  lane :deploy_to_firebase do
    sh "echo \"$ENV['FIREBASE_CLI_TOKEN']\""
    sh "flutter build apk --release"
    # Étape de déploiement sur Firebase App Distribution
    firebase_app_distribution(
      app: "1:1029177077570:android:45412d04da3eab14c1a2db",
      groups: "testygroup",
      release_notes: "Version 2.0.0",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      debug: false,
      android_artifact_type: "APK",
      firebase_cli_path: "/usr/local/bin/firebase",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
    )
  end
end