name: Flutter App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'  # Remplacez par votre version de Flutter

      - name: Install Fastlane
        run: gem install bundler && bundle install

      - name: Build and deploy to Firebase App Distribution
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          fastlane run build_flutter_app
          fastlane run deploy_to_firebase
