name: Flutter App Distribution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'use java11'
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'  # Remplacez par votre version de Flutter

      - name: Install Fastlane
        run: gem install bundler && bundle install

      - name: Fastlane versions
        run: fastlane --version

      - name: Build and deploy to Firebase App Distribution
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          fastlane build_flutter_app
          fastlane deploy_to_firebase
